package com.exam;
// Generated Apr 7, 2019 12:05:28 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 * Patientbook generated by hbm2java
 */
@ManagedBean(name = "book")
@SessionScoped
public class Patientbook implements java.io.Serializable {

    List<Patientbook> all = new ArrayList<>();

    public List<Patientbook> getAll() {
        PatientbookDao ad = new PatientbookDao();
        all = ad.showAll();
        return all;
    }

    public void setAll(List<Patientbook> all) {
        this.all = all;
    }

    private int appointId;
    private String category;
    private String type;
    private String bdate;
    private String time;
    private String patientId;
    private String doctorName;

    public Patientbook() {
    }

    public Patientbook(int appointId) {
        this.appointId = appointId;
    }

    public Patientbook(int appointId, String category, String type, String bdate, String time, String patientId, String doctorName) {
        this.appointId = appointId;
        this.category = category;
        this.type = type;
        this.bdate = bdate;
        this.time = time;
        this.patientId = patientId;
        this.doctorName = doctorName;
    }

    public int getAppointId() {
        return this.appointId;
    }

    public void setAppointId(int appointId) {
        this.appointId = appointId;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getBdate() {
        return this.bdate;
    }

    public void setBdate(String bdate) {
        this.bdate = bdate;
    }

    public String getTime() {
        return this.time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getPatientId() {
        return this.patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getDoctorName() {
        return this.doctorName;
    }

    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    public void doBook() {
        PatientbookDao pb = new PatientbookDao();
        pb.doSave(this);
    }

}
